name: Build Bionic Docker
on: [push]
jobs:
  bionic:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          context: bionic
          push: true
          tags: pasbi/ommpfritt-bionic:latest
  focal:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          context: focal
          push: true
          tags: pasbi/ommpfritt-focal:latest
